server:
  port: 8888
spring:
  profiles:
    active:
  redis:
    password: zhg99524
    host: 114.115.208.62
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://114.115.208.62:3306/permission?useUnicode=true&characterEncoding=utf-8
    password: zhg99524
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
