server:
  port: 8887
spring:
  redis:
    password: zhg99524
    host: tx.unclezs.com
    database: 0
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${spring.redis.host}:3306/permission?useUnicode=true&characterEncoding=utf-8
    username: permission
    password: zhg99524
logging:
  level:
    com.unclezs.permission.module.system.mapper: debug
